#!/usr/bin/python3 -cimport os, sys; os.execv(os.path.dirname(sys.argv[1]) + "/common/pywrap", sys.argv)

# Run this with --help to see available options for tracing and debugging
# See https://github.com/cockpit-project/cockpit/blob/main/test/common/testlib.py
# "class Browser" and "class MachineCase" for the available API.

import testlib


# Nondestructive tests all run in the same running VM. This allows them to run in Packit, Fedora, and
# RHEL dist-git gating. They must not permanently change any file or configuration on the system in a
# way that influences other tests.
@testlib.nondestructive
class TestApplication(testlib.MachineCase):
    def testBasic(self):
        b = self.browser

        self.login_and_go("/storage")
        # verify the storage page opens with the filesystem picker
        b.wait_text(".pf-v6-c-card__title", "Disk Usage")
        b.wait_visible("[data-testid=filesystem]")

        # pick the root filesystem and verify the drill-down treemap appears
        b.click("[data-testid=filesystem]")
        b.wait_visible("[data-testid=treemap]")
        b.wait_visible("[aria-label=breadcrumb]")

        # navigate back to the filesystem picker
        b.click("button:contains(Back)")
        b.wait_visible("[data-testid=filesystem]")

        # change language to German and verify the translated menu label
        b.switch_to_top()
        b.click("#toggle-menu")
        b.click("button.display-language-menu")
        b.wait_popup('display-language-modal')
        b.click("#display-language-modal [data-value='de-de'] button")
        b.click("#display-language-modal button.pf-m-primary")
        b.wait_visible("#content")
        b.wait_text("#host-apps a[href='/storage']", "Speicher")


if __name__ == '__main__':
    testlib.test_main()
